[build]
command = "bundle exec jekyll build --config '_config.yml,_config_staging.yml'"
publish = "_site"

[build.environment]
RUBY_VERSION = "2.6.2"

[[redirects]]
  from = "/"
  to = "/aria-practices/"
