name: Deploy to netlify from APG trigger

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        cache: npm
        cache-dependency-path: scripts/pre-build/package-lock.json

    - name: Set up Ruby 2.6.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.2
        bundler-cache: true

    - name: Update git submodules
      run: |
        git submodule update --recursive --remote

    - name: Update site files
      run: |
        bundle install
        npm install -C scripts/pre-build
        node ./scripts/pre-build

    - name: Commit changed files and submodule updates
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Commit changes
        branch: main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
